import { execFile } from "node:child_process";
import { writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

export interface VibeCheckScores {
  originality: number;
  layout: number;
  typography: number;
  color: number;
  overall: number;
}

export interface VibeCheckResult {
  scores: VibeCheckScores;
  vibe_coded_probability: number;
  roast: string;
  red_flags: string[];
  good_parts: string[];
  verdict: string;
  savage_rating?: number;
  tweet?: string;
}

const PROMPT = `You are VIBECHECK — a brutally honest UI design critic who roasts websites.
You analyze screenshots and score them on how generic / "vibe-coded" they look.

You MUST respond with ONLY valid JSON (no markdown, no backticks, no explanation outside the JSON).

The JSON schema:

{
  "scores": {
    "originality": <0-100>,
    "layout": <0-100>,
    "typography": <0-100>,
    "color": <0-100>,
    "overall": <0-100>
  },
  "vibe_coded_probability": <0-100>,
  "roast": "<A savage 1-2 sentence roast of the design. Be funny, specific, and cutting. Reference actual elements you see.>",
  "red_flags": ["<specific generic pattern spotted>", ...],
  "good_parts": ["<anything genuinely good>", ...],
  "verdict": "<CERTIFIED ORIGINAL | MOSTLY FRESH | KINDA MID | GENERIC AF | VIBE-CODED CLONE>"
}

Scoring guide:
- originality: Does this look like it was designed by a human with taste, or generated by an AI that only knows purple gradients and glassmorphism? 100 = truly unique. 0 = template city.
- layout: Is the layout interesting or is it the classic Hero → Features Grid → Pricing → Footer? Creative layouts score high. "I've seen this 10000 times" scores low.
- typography: Is there typographic craft? Custom fonts, good hierarchy, interesting sizing? Or is it default Inter with random font-weights?
- color: Intentional palette or the default purple/blue gradient + white cards?
- overall: Weighted average with originality counting 2x.

Red flags to look for:
- Purple/blue gradients on hero sections
- Glassmorphism cards with blur backgrounds
- "Hero → Features → Testimonials → Pricing → Footer" layout
- Generic stock illustrations or 3D blob shapes
- "Get Started" / "Start Free Trial" buttons that look identical to every SaaS
- Excessive rounded corners on everything
- Dark mode with neon accents (the "developer tool" starter pack)
- Grid of 3 feature cards with icons
- Floating mockup screenshots at an angle
- "Trusted by" logo bars
- Gradient text on headings

Be SPECIFIC about what you see. Don't be generic in your roast — reference actual colors, elements, copy you can read in the screenshot.

Look at the attached screenshot and analyze it. Respond with ONLY the JSON object.`;

const ROAST_PROMPT_EXTRA = `

YOU ARE IN MAXIMUM ROAST MODE. Be absolutely brutal. No mercy. Hold nothing back.

Your roast should be 3-4 sentences of pure devastation. Think "comedy central roast" meets "Gordon Ramsay looking at a microwave dinner." Be specific about what you see — call out exact colors, fonts, layouts, and copy. Make it personal.

In addition to the standard fields, you MUST also include:
- "savage_rating": a number from 1-10 rating how truly awful this site is (10 = crime against design)
- "tweet": a ready-to-copy tweet roasting this site in under 280 characters. Make it viral-worthy. Include the site name if visible.

The roast field should be MUCH more savage than normal. Think: devastating, quotable, screenshot-worthy burns.`;

export async function analyzeScreenshot(screenshotBuffer: Buffer, roastMode: boolean = false): Promise<VibeCheckResult> {
  // Write screenshot to a temp file so claude can read it
  const tmpPath = join(tmpdir(), `vibecheck-${Date.now()}.png`);
  writeFileSync(tmpPath, screenshotBuffer);

  try {
    const promptText = roastMode ? PROMPT + ROAST_PROMPT_EXTRA : PROMPT;
    const fullPrompt = `Read the screenshot at ${tmpPath} and analyze it.\n\n${promptText}`;
    const result = await new Promise<string>((resolve, reject) => {
      execFile(
        "claude",
        ["-p", fullPrompt, "--output-format", "json", "--allowedTools", "Read"],
        { maxBuffer: 1024 * 1024, timeout: 120000 },
        (err: Error | null, stdout: string, _stderr: string) => {
          if (err) return reject(new Error(`claude CLI failed: ${err.message}`));
          try {
            const parsed = JSON.parse(stdout);
            resolve(parsed.result);
          } catch {
            reject(new Error(`Failed to parse claude output: ${stdout.slice(0, 200)}`));
          }
        }
      );
    });

    // result is the text response from claude — extract JSON from it
    // Claude might wrap it in markdown fences or add text around it
    let jsonStr: string = typeof result === "object" ? JSON.stringify(result) : result;

    // Try to find a JSON object in the response
    const jsonMatch = jsonStr.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      jsonStr = jsonMatch[0];
    }

    return JSON.parse(jsonStr) as VibeCheckResult;
  } finally {
    try { unlinkSync(tmpPath); } catch {}
  }
}
