export interface HeuristicResult {
  scores: {
    originality: number;
    layout: number;
    typography: number;
    color: number;
    overall: number;
  };
  vibe_coded_probability: number;
  roast: string;
  red_flags: string[];
  good_parts: string[];
  verdict: string;
}

export function analyzeHeuristic(screenshotBuffer: Buffer): HeuristicResult {
  // We can't do full image analysis without sharp/canvas,
  // but we can analyze the raw PNG bytes for color patterns

  const red_flags: string[] = [];
  const good_parts: string[] = [];

  // Sample colors from the PNG buffer
  // PNG has a signature (8 bytes), then chunks
  // We'll look at raw byte distribution for color analysis
  const bytes = screenshotBuffer;

  // Count byte value distributions to detect patterns
  let darkPixels = 0;
  let purpleHue = 0;
  let blueHue = 0;
  let totalSamples = 0;

  // Sample every 100th byte triplet after the PNG header
  for (let i = 100; i < bytes.length - 3; i += 300) {
    const r = bytes[i];
    const g = bytes[i + 1];
    const b = bytes[i + 2];
    totalSamples++;

    // Dark pixel detection
    if (r < 40 && g < 40 && b < 40) darkPixels++;

    // Purple detection (high red + high blue, low green)
    if (r > 100 && b > 100 && g < 80) purpleHue++;

    // Blue detection
    if (b > 150 && r < 100 && g < 100) blueHue++;
  }

  if (totalSamples === 0) totalSamples = 1;

  const darkRatio = darkPixels / totalSamples;
  const purpleRatio = purpleHue / totalSamples;
  const blueRatio = blueHue / totalSamples;

  // Scoring
  let originality = 50;
  let layout = 50;
  let color = 50;
  let typography = 50;

  // Dark mode detection
  if (darkRatio > 0.5) {
    red_flags.push('Dark mode detected — the "developer tool" starter pack');
    originality -= 10;
  }

  // Purple gradient detection
  if (purpleRatio > 0.05) {
    red_flags.push("Purple/violet hues detected — classic vibe-coded gradient");
    color -= 20;
    originality -= 15;
  }

  // Heavy blue
  if (blueRatio > 0.1) {
    red_flags.push("Heavy blue palette — the SaaS default");
    color -= 10;
  }

  // File size as a proxy for complexity (bigger = more content/images)
  const sizeKB = bytes.length / 1024;
  if (sizeKB < 100) {
    red_flags.push("Very minimal page content (small screenshot)");
    layout -= 10;
  } else if (sizeKB > 500) {
    good_parts.push("Rich visual content detected");
    layout += 10;
  }

  // If no red flags, give credit
  if (red_flags.length === 0) {
    good_parts.push("No obvious vibe-coded patterns detected");
    originality += 15;
  }

  // If not dark and not purple, that's good
  if (darkRatio < 0.3 && purpleRatio < 0.02) {
    good_parts.push("Not using the generic dark + purple combo");
    color += 10;
    originality += 10;
  }

  // Clamp scores
  originality = Math.max(0, Math.min(100, originality));
  layout = Math.max(0, Math.min(100, layout));
  typography = Math.max(0, Math.min(100, typography));
  color = Math.max(0, Math.min(100, color));

  const overall = Math.round(
    (originality * 2 + layout + typography + color) / 5
  );

  const vibe_coded_probability = Math.max(
    0,
    Math.min(
      100,
      Math.round(
        50 +
          purpleRatio * 200 +
          (darkRatio > 0.5 ? 15 : 0) -
          (red_flags.length === 0 ? 20 : 0)
      )
    )
  );

  // Generate roast
  const roast =
    red_flags.length === 0
      ? "Surprisingly, this doesn't look like it was generated by an AI having a purple gradient fever dream. Respect."
      : `Detected ${red_flags.length} red flag${red_flags.length > 1 ? "s" : ""}. This site has "I prompted it in 20 minutes" energy.`;

  // Determine verdict
  let verdict: string;
  if (overall >= 80) verdict = "CERTIFIED ORIGINAL";
  else if (overall >= 65) verdict = "MOSTLY FRESH";
  else if (overall >= 45) verdict = "KINDA MID";
  else if (overall >= 25) verdict = "GENERIC AF";
  else verdict = "VIBE-CODED CLONE";

  return {
    scores: { originality, layout, typography, color, overall },
    vibe_coded_probability,
    roast,
    red_flags,
    good_parts: good_parts.length > 0 ? good_parts : ["At least it loads"],
    verdict,
  };
}
